name: Check NVIDIA Driver Version

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-driver-version:
    runs-on: ubuntu-latest
    outputs:
      driver_version: ${{ steps.check-version.outputs.driver_version }}
      update_available: ${{ steps.check-version.outputs.update_available }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check latest NVIDIA driver version
        id: check-version
        run: |
          # Get the latest version
          latest_driver=$(curl -s https://download.nvidia.com/XFree86/Linux-x86_64/latest.txt | awk '{print $2}')
          latest_version=$(echo "$latest_driver" | cut -d'/' -f2 | sed 's/NVIDIA-Linux-x86_64-\(.*\).run/\1/')
          echo "Latest driver version: $latest_version"
          echo "driver_version=$latest_version" >> $GITHUB_OUTPUT

          # Check if we need to build a new template
          if [ -f "last_built_version.txt" ]; then
            last_version=$(cat last_built_version.txt)
            if [ "$latest_version" != "$last_version" ]; then
              echo "New driver version detected: $latest_version (previous: $last_version)"
              echo "update_available=true" >> $GITHUB_OUTPUT
            else
              echo "No new driver version available"
              echo "update_available=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous version found, building new template"
            echo "update_available=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build if new version is available
        if: steps.check-version.outputs.update_available == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-new-template
          client-payload: '{"driver_version": "${{ steps.check-version.outputs.driver_version }}"}'